1.10 update
mesosphere/cd-demo pull request #42
Opened 2017-08-15 21:09 UTC by sschneid

2017-09-08 20:01 UTC, colin-msphere commented on conf/cd-demo-app.json
> +        "servicePort": 10101,
`servicePort` should probably be left out so the system can choose a random unused port.

2017-09-08 20:01 UTC, colin-msphere commented on conf/cd-demo-app.json
> +    "lastChangedBy": "velocity-team@mesosphere.com"
This can be removed.

2017-09-08 20:02 UTC, colin-msphere requested changes
Two changes for the app definition.

2017-09-11 16:56 UTC, sschneid commented
> Two changes for the app definition.

Updated!

2017-09-11 18:26 UTC, colin-msphere approved these changes

2017-09-11 18:26 UTC, merged